### ISSUE TITLE
Unable to start the web server

### ISSUE THREAD

**Issue by javidhsueh** [uber-web/ocular#53]
Every time when I install Ocular through yarn/npm, there's always an error that unable to start the web server:

`> ocular start

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/javidhsueh/graph.gl/docs/node_modules/.bin/webpack-dev-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! graphgl@0.0.0 start: `ocular start`
npm ERR! Exit status 1`

The error is because the alias file 'webpack-dev-server' doesn't exist in node_modules/.bin folder

**Comment by ibgreen** [comment]
Not reproduced
